INSERT INTO URL (URL,TOKEN,DATE_ADD,DATE_END) VALUES ('test.ru', 'FGHYTR', now(), now());
INSERT INTO URL (URL,TOKEN,DATE_ADD,DATE_END) VALUES ('test.ru1', 'FGHYTR1', now() - INTERVAL '1 DAY', now() - INTERVAL '1 DAY');
INSERT INTO URL (URL,TOKEN,DATE_ADD,DATE_END) VALUES ('test.ru2', 'FGHYTR2', now() - INTERVAL '1 DAY', now() - INTERVAL '1 DAY');