CREATE TABLE IF NOT EXISTS URL
(
    ID       BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    URL      VARCHAR,
    TOKEN    VARCHAR(100)/* NOT NULL*/,
    DATE_ADD DATE DEFAULT CURRENT_DATE,
    DATE_END DATE    NOT NULL,
    UNIQUE (URL),
    UNIQUE (TOKEN)
);

CREATE INDEX IX_URL_URL ON URL (URL);
CREATE INDEX IX_URL_TOKEN ON URL (TOKEN);